root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main cmd/web/main.go"
bin = "./tmp/main"
include_ext = ["go", "templ"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
send_interrupt = false

[log]
time = true

[screen]
clear_on_rebuild = true
