root = "."
tmp_dir = "tmp"

[build]
    cmd = "templ generate && go run ."
    bin = "./tmp/main"
    exclude_regex = [".*_templ.go"]
    include_ext = ["go", "tpl", "tmpl", "templ", "html"]
    exclude_dir = ["assets", "tmp", "vendor"]
    include_dir = []
    exclude_file = []
    delay = 1000
    stop_on_error = true
    send_interrupt = false
    kill_delay = "0s"
    log = "build-errors.log"

[color]
    app = ""
    build = "yellow"
    main = "magenta"
    runner = "green"
    watcher = "cyan"

[log]
    time = true

[screen]
    clear_on_rebuild = true

[misc]
    clean_on_exit = false